# Cualquier archivo que se encuentre en el directorio .github/workflows
# Nombre de workflow
name: Hola Mundo

# Evento que se va a ejecutar
on: [push]


# se ejecutará cuando se ejecute el evento
jobs:
  #  Job que se ejecutará
  hola:
    #   Run: comando que se ejecutará sobre el servidor de GitHub Actions
    runs-on: ubuntu-latest

    #   Steps: conjunto de acciones que se ejecutarán
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

      - name: touch file
        run: touch hola.txt

      - name: Set text
        run: echo "Hola Mundo" >> hola.txt

      - name: Read file
        run: cat hola.txt


  #   Job que se ejecutará
  other:
    #   Run: comando que se ejecutará sobre el servidor de GitHub Actions
    runs-on: ubuntu-latest

    #     Steps: conjunto de acciones que se ejecutarán
    steps:
    - name: LS
      run: touch hola.txt

  paquete:
    runs-on: ubuntu-latest
    
    steps:
      # plugin checkout de git hub intregrado
    - name: Checkout
      uses: actions/checkout@v4.2.1
      #Llamada para agregar el paquete en el archivo instalar.sh 
    - name: ls
      run: |
        chmod  +x instalar.sh
        ./instalar.sh



